// Copyright 2022, Qwacks. Licensed under the MIT License - see LICENSE.md.

#include "Codegen/FlockCppTypeEmitter.h"

#include "Codegen/FlockEnumEmitter.h"
#include "Codegen/FlockSchemaTypes.h"
#include "Codegen/FlockStructEmitter.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace
{
	// No copyright line: this banner goes into files generated in the *user's* project, from their own
	// schema. Asserting the SDK's copyright over their content model would be wrong, and pointing at a
	// LICENSE.md that lives in the plugin would dangle.
	const TCHAR* const Banner =
		TEXT("// <auto-generated>\n")
		TEXT("//   Generated by Flock. Do not edit by hand — a schema sync replaces this file.\n")
		TEXT("// </auto-generated>\n");

	const TCHAR* const PropertyLine =
		TEXT("\tUPROPERTY(BlueprintReadWrite, EditAnywhere, Category = \"Flock|Generated\")\n");

	/**
	 * Words a member cannot be called.
	 *
	 * C++ keywords, plus the handful of Unreal macros that expand at member scope. A field named `class`
	 * is legal on the dashboard and legal in Blueprint; only here does it stop the project compiling, so
	 * only here is it skipped.
	 */
	bool IsReservedWord(const FString& Name)
	{
		static const TSet<FString> Reserved = {
			TEXT("alignas"), TEXT("alignof"), TEXT("and"), TEXT("asm"), TEXT("auto"), TEXT("bool"),
			TEXT("break"), TEXT("case"), TEXT("catch"), TEXT("char"), TEXT("class"), TEXT("const"),
			TEXT("constexpr"), TEXT("continue"), TEXT("decltype"), TEXT("default"), TEXT("delete"),
			TEXT("do"), TEXT("double"), TEXT("else"), TEXT("enum"), TEXT("explicit"), TEXT("export"),
			TEXT("extern"), TEXT("false"), TEXT("float"), TEXT("for"), TEXT("friend"), TEXT("goto"),
			TEXT("if"), TEXT("inline"), TEXT("int"), TEXT("long"), TEXT("mutable"), TEXT("namespace"),
			TEXT("new"), TEXT("noexcept"), TEXT("not"), TEXT("nullptr"), TEXT("operator"), TEXT("or"),
			TEXT("private"), TEXT("protected"), TEXT("public"), TEXT("register"), TEXT("return"),
			TEXT("short"), TEXT("signed"), TEXT("sizeof"), TEXT("static"), TEXT("struct"), TEXT("switch"),
			TEXT("template"), TEXT("this"), TEXT("throw"), TEXT("true"), TEXT("try"), TEXT("typedef"),
			TEXT("typename"), TEXT("union"), TEXT("unsigned"), TEXT("using"), TEXT("virtual"), TEXT("void"),
			TEXT("volatile"), TEXT("while"), TEXT("xor"),
			// Unreal's own, which expand at member scope and would not survive a member of the same name.
			TEXT("UPROPERTY"), TEXT("UFUNCTION"), TEXT("USTRUCT"), TEXT("UCLASS"), TEXT("UENUM"),
			TEXT("GENERATED_BODY"), TEXT("TEXT"),
		};
		// Case-sensitively: `TSet<FString>` compares case-insensitively by default, which would reject
		// `Class` for colliding with the keyword `class` — a legal identifier, and exactly what
		// Pascal-casing a field named `class` produces. Only the exact spelling is reserved.
		for (const FString& Word : Reserved)
		{
			if (Name.Equals(Word, ESearchCase::CaseSensitive))
			{
				return true;
			}
		}
		return false;
	}

	/** "Player Level" -> "PlayerLevel". Identifier-safe; a leading digit gets an underscore. */
	FString PascalCase(const FString& Source)
	{
		FString Pascal;
		bool bUpperNext = true;
		for (const TCHAR Character : Source)
		{
			if (FChar::IsAlnum(Character))
			{
				Pascal.AppendChar(bUpperNext ? FChar::ToUpper(Character) : Character);
				bUpperNext = false;
			}
			else
			{
				bUpperNext = true;
			}
		}
		if (Pascal.IsEmpty())
		{
			return TEXT("Unnamed");
		}
		return FChar::IsDigit(Pascal[0]) ? TEXT("_") + Pascal : Pascal;
	}

	/** One emitted struct, held until every nested type it depends on has been written before it. */
	struct FStructText
	{
		FString Name;
		FString Body;
	};

	/**
	 * Builds a struct and everything nested inside it, appending each **dependency first**.
	 *
	 * The ordering is not cosmetic: UHT will not accept a `USTRUCT` declared inside another, so a nested
	 * object becomes its own top-level struct — and C++ needs that definition to appear before the member
	 * that uses it.
	 */
	using FWireNamesByStruct = TMap<FString, TMap<FString, FString>>;

	FString ResolveMemberType(const TSharedRef<FJsonObject>& Field, const FString& NamePrefix, int32 Depth,
		const FString& ModuleApi, TArray<FStructText>& InOutStructs, FWireNamesByStruct& OutWireNames,
		TArray<FString>& OutWarnings);

	FString BuildStruct(const FString& StructName, const TArray<TSharedPtr<FJsonValue>>& Entries, int32 Depth,
		const FString& ModuleApi, const FString& Comment, TArray<FStructText>& InOutStructs,
		FWireNamesByStruct& OutWireNames, TArray<FString>& OutWarnings)
	{
		FString Members;
		int32 Added = 0;

		for (const TSharedPtr<FJsonValue>& Entry : Entries)
		{
			const TSharedPtr<FJsonObject> Field = Entry.IsValid() ? Entry->AsObject() : nullptr;
			if (!Field.IsValid())
			{
				continue;
			}
			FString DeclaredName;
			if (!Field->TryGetStringField(TEXT("field_name"), DeclaredName) || DeclaredName.IsEmpty())
			{
				continue;
			}
			// Pascal-cased so C++ reads idiomatically (`GameCurrencies`, not `game_currencies`). Renaming
			// is only safe because the declared name travels separately in the wire-name registry — the
			// member is what you type, the registered name is what the server sees. Without that map a
			// rename silently writes a key the server rejects, which is why the Blueprint tier, which has
			// no such map, keeps declared names verbatim.
			const FString MemberName = PascalCase(DeclaredName);
			if (!FFlockCppTypeEmitter::IsUsableMemberName(MemberName))
			{
				OutWarnings.Add(FString::Printf(
					TEXT("'%s.%s': field name cannot be made into a legal C++ member name, so it was skipped. ")
					TEXT("Rename it on the dashboard to use it from C++."), *StructName, *DeclaredName));
				continue;
			}
			if (!MemberName.Equals(DeclaredName, ESearchCase::CaseSensitive))
			{
				OutWireNames.FindOrAdd(StructName).Add(MemberName, DeclaredName);
			}

			const FString MemberType = ResolveMemberType(Field.ToSharedRef(),
				StructName + MemberName, Depth, ModuleApi, InOutStructs, OutWireNames, OutWarnings);

			// Default-initialized so an unfetched struct is zeroed rather than holding stack garbage.
			// FString/TArray/TMap default themselves; only the scalars need it spelled out.
			FString Initializer;
			if (MemberType == TEXT("int32") || MemberType == TEXT("int64"))
			{
				Initializer = TEXT(" = 0");
			}
			else if (MemberType == TEXT("float") || MemberType == TEXT("double"))
			{
				Initializer = TEXT(" = 0.f");
			}
			else if (MemberType == TEXT("bool"))
			{
				Initializer = TEXT(" = false");
			}

			Members += PropertyLine;
			Members += FString::Printf(TEXT("\t%s %s%s;\n\n"), *MemberType, *MemberName, *Initializer);
			++Added;
		}

		if (Added == 0)
		{
			// Emitted anyway rather than skipped: something references this type by name, and a struct
			// that is merely empty compiles while a missing one does not.
			OutWarnings.Add(FString::Printf(TEXT("'%s': no usable fields; the struct is empty."), *StructName));
		}

		FString Body;
		Body += FString::Printf(TEXT("/** %s */\n"), *Comment);
		Body += TEXT("USTRUCT(BlueprintType)\n");
		Body += FString::Printf(TEXT("struct %s %s\n{\n\tGENERATED_BODY()\n\n"), *ModuleApi, *StructName);
		Body += Members;
		Body += TEXT("};\n");

		InOutStructs.Add({ StructName, Body });
		return StructName;
	}

	FString ResolveMemberType(const TSharedRef<FJsonObject>& Field, const FString& NamePrefix, int32 Depth,
		const FString& ModuleApi, TArray<FStructText>& InOutStructs, FWireNamesByStruct& OutWireNames,
		TArray<FString>& OutWarnings)
	{
		FString WireType;
		Field->TryGetStringField(TEXT("type"), WireType);

		switch (FFlockSchemaTypes::Classify(WireType))
		{
		case EFlockSchemaKind::String:  return TEXT("FString");
		case EFlockSchemaKind::Int:     return TEXT("int32");
		case EFlockSchemaKind::Int64:   return TEXT("int64");
		case EFlockSchemaKind::Float:   return TEXT("float");
		case EFlockSchemaKind::Double:  return TEXT("double");
		case EFlockSchemaKind::Bool:    return TEXT("bool");
		default: break;
		}

		if (Depth >= FFlockSchemaTypes::MaxNestingDepth)
		{
			OutWarnings.Add(FString::Printf(
				TEXT("'%s': nested more than %d deep; emitted as an opaque JSON handle."),
				*NamePrefix, FFlockSchemaTypes::MaxNestingDepth));
			return TEXT("FFlockJsonData");
		}

		const EFlockSchemaKind Kind = FFlockSchemaTypes::Classify(WireType);
		const TArray<TSharedPtr<FJsonValue>> Children = FFlockSchemaTypes::ChildEntries(Field);

		if (Kind == EFlockSchemaKind::Object)
		{
			if (Children.IsEmpty())
			{
				OutWarnings.Add(FString::Printf(
					TEXT("'%s': object with no declared body; emitted as an opaque JSON handle."), *NamePrefix));
				return TEXT("FFlockJsonData");
			}
			// Appends the nested struct to the list before returning, so it is written out first.
			return BuildStruct(TEXT("F") + NamePrefix.RightChop(1), Children, Depth + 1, ModuleApi,
				FString::Printf(TEXT("Nested object `%s`."), *NamePrefix), InOutStructs, OutWireNames,
				OutWarnings);
		}

		if (Kind == EFlockSchemaKind::List || Kind == EFlockSchemaKind::Dict)
		{
			const TSharedPtr<FJsonObject> Element = Children.IsEmpty() ? nullptr : Children[0]->AsObject();
			if (!Element.IsValid())
			{
				OutWarnings.Add(FString::Printf(
					TEXT("'%s': container with no declared element type; emitted as an opaque JSON handle."),
					*NamePrefix));
				return TEXT("FFlockJsonData");
			}

			const FString ElementType = ResolveMemberType(Element.ToSharedRef(), NamePrefix + TEXT("Item"),
				Depth + 1, ModuleApi, InOutStructs, OutWireNames, OutWarnings);

			// UHT rejects a container whose element is itself a container, so this degrades rather than
			// producing a header that fails the user's build.
			if (ElementType.StartsWith(TEXT("TArray<")) || ElementType.StartsWith(TEXT("TMap<")))
			{
				OutWarnings.Add(FString::Printf(
					TEXT("'%s': a container of containers is not expressible as a UPROPERTY; ")
					TEXT("emitted as an opaque JSON handle."), *NamePrefix));
				return TEXT("FFlockJsonData");
			}

			// Dict keys are author data and always arrive as strings.
			return Kind == EFlockSchemaKind::Dict
				? FString::Printf(TEXT("TMap<FString, %s>"), *ElementType)
				: FString::Printf(TEXT("TArray<%s>"), *ElementType);
		}

		OutWarnings.Add(FString::Printf(
			TEXT("'%s': unrecognized type '%s'; emitted as an opaque JSON handle."), *NamePrefix, *WireType));
		return TEXT("FFlockJsonData");
	}

	bool WriteIfChanged(const FString& Path, const FString& Content, FString& OutError)
	{
		FString Existing;
		if (FFileHelper::LoadFileToString(Existing, *Path) && Existing.Equals(Content, ESearchCase::CaseSensitive))
		{
			return true;
		}
		if (!FFileHelper::SaveStringToFile(Content, *Path, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			OutError = FString::Printf(TEXT("Could not write '%s'. Is it read-only?"), *Path);
			return false;
		}
		return true;
	}

	/** Wraps emitted struct bodies in a header, with the includes those bodies need. */
	FString HeaderFor(const FString& HeaderName, const TArray<FStructText>& Structs)
	{
		FString Text = Banner;
		Text += TEXT("\n#pragma once\n\n");
		Text += TEXT("#include \"CoreMinimal.h\"\n");
		// Always included: any field can degrade to the opaque handle, and an unused include is free
		// where a missing one is a build break.
		Text += TEXT("#include \"Models/FlockJsonData.h\"\n");
		Text += FString::Printf(TEXT("#include \"%s.generated.h\"\n\n"), *HeaderName);
		for (const FStructText& Struct : Structs)
		{
			Text += Struct.Body;
			Text += TEXT("\n");
		}
		return Text;
	}

	/** One `UENUM` plus the inline lookup turning a picked member into the string the SDK sends. */
	FString EnumHeaderFor(const FString& HeaderName, const FString& EnumName,
		const TArray<TPair<FString, FString>>& Members)
	{
		FString Text = Banner;
		Text += TEXT("\n#pragma once\n\n");
		Text += TEXT("#include \"CoreMinimal.h\"\n");
		Text += FString::Printf(TEXT("#include \"%s.generated.h\"\n\n"), *HeaderName);

		// uint8, because UENUM(BlueprintType) requires it — so the generated enum is usable from a graph
		// as well as from C++.
		Text += FString::Printf(TEXT("/** Every %s this game version declares. */\n"), *EnumName);
		Text += TEXT("UENUM(BlueprintType)\n");
		Text += FString::Printf(TEXT("enum class E%s : uint8\n{\n"), *EnumName);
		for (const TPair<FString, FString>& Member : Members)
		{
			Text += FString::Printf(TEXT("\t%s,\n"), *Member.Key);
		}
		Text += TEXT("};\n\n");

		// The display name is not the wire value — an item shows as `GemPack` but purchases by an opaque
		// id — so the mapping is baked here rather than looked up at runtime. Inline, so the enum needs
		// no .cpp and the module stays header-only.
		Text += FString::Printf(
			TEXT("/** The id or name the SDK sends for a picked member. */\n")
			TEXT("inline FString %sToWire(E%s Value)\n{\n\tswitch (Value)\n\t{\n"), *EnumName, *EnumName);
		for (const TPair<FString, FString>& Member : Members)
		{
			Text += FString::Printf(TEXT("\tcase E%s::%s: return TEXT(\"%s\");\n"),
				*EnumName, *Member.Key, *Member.Value);
		}
		Text += TEXT("\tdefault: return FString();\n\t}\n}\n");
		return Text;
	}
}

FString FFlockCppTypeEmitter::MakeStructName(const FString& EntityName, const TCHAR* Suffix)
{
	return TEXT("F") + PascalCase(EntityName) + Suffix;
}

bool FFlockCppTypeEmitter::IsUsableMemberName(const FString& DeclaredName)
{
	if (DeclaredName.IsEmpty())
	{
		return false;
	}
	if (!FChar::IsAlpha(DeclaredName[0]) && DeclaredName[0] != TEXT('_'))
	{
		return false;
	}
	for (const TCHAR Character : DeclaredName)
	{
		if (!FChar::IsAlnum(Character) && Character != TEXT('_'))
		{
			return false;
		}
	}
	return !IsReservedWord(DeclaredName);
}

FFlockCppTypeEmitter::FEmitResult FFlockCppTypeEmitter::Emit(const FFlockSchemaSnapshot& Snapshot,
	const FString& GeneratedRoot, const FString& ModuleName)
{
	FEmitResult Result;
	const FString PublicDir = FPaths::Combine(GeneratedRoot, TEXT("Public"));
	IFileManager::Get().MakeDirectory(*PublicDir, /*Tree*/ true);

	// Generated headers are wholly owned, so the previous set goes rather than accumulating — a template
	// deleted on the backend must lose its header, or the module still compiles a type that no longer
	// exists. The manifest and module files are named differently and are left alone.
	const FString ManifestHeader = ModuleName + TEXT("Manifest.h");
	TArray<FString> Existing;
	IFileManager::Get().FindFiles(Existing, *FPaths::Combine(PublicDir, TEXT("*.h")), /*Files*/ true, /*Dirs*/ false);
	for (const FString& File : Existing)
	{
		// The manifest header belongs to the module skeleton, not to this emitter, and removing it would
		// leave anything including it uncompilable until the next full sync.
		if (File.Equals(ManifestHeader, ESearchCase::IgnoreCase))
		{
			continue;
		}
		IFileManager::Get().Delete(*FPaths::Combine(PublicDir, File));
	}

	const FString ModuleApi = ModuleName.ToUpper() + TEXT("_API");
	FWireNamesByStruct WireNames;

	auto EmitEntity = [&](const FString& EntityName, const FString& SchemaJson, const TCHAR* Suffix,
		const TCHAR* Kind)
	{
		const FString StructName = MakeStructName(EntityName, Suffix);
		TArray<FStructText> Structs;
		BuildStruct(StructName, FFlockSchemaTypes::ParseSchemaArray(SchemaJson), /*Depth*/ 0, ModuleApi,
			FString::Printf(TEXT("The \"%s\" %s."), *EntityName, Kind), Structs, WireNames, Result.Warnings);

		// Nested structs were appended before their parent, which is the order C++ needs.
		const FString HeaderName = StructName;
		FString WriteError;
		if (!WriteIfChanged(FPaths::Combine(PublicDir, HeaderName + TEXT(".h")),
			HeaderFor(HeaderName, Structs), WriteError))
		{
			Result.Warnings.Add(WriteError);
			return;
		}
		Result.Headers.Add(HeaderName + TEXT(".h"));
		Result.StructCount += Structs.Num();
	};

	for (const FFlockPlayerTemplateSchema& Template : Snapshot.PlayerTemplates)
	{
		EmitEntity(Template.Name, Template.SchemaJson, FFlockStructEmitter::TemplateSuffix, TEXT("player template"));
	}
	for (const FFlockGameConfigSchema& Config : Snapshot.GameConfigs)
	{
		EmitEntity(Config.Name, Config.SchemaJson, FFlockStructEmitter::ConfigSuffix, TEXT("game config"));
	}

	// The enums, from the same member sets the Blueprint target uses — so an id means the same thing
	// whichever target a project picked.
	auto EmitEnum = [&](const TCHAR* EnumName, const TArray<TPair<FString, FString>>& Members)
	{
		// An enum with no members is not a useful dropdown, and an empty `enum class` is a compile error
		// in a switch — so a game with no shop simply gets no shop enum.
		if (Members.IsEmpty())
		{
			return;
		}
		const FString HeaderName = EnumName;
		FString WriteError;
		if (!WriteIfChanged(FPaths::Combine(PublicDir, HeaderName + TEXT(".h")),
			EnumHeaderFor(HeaderName, EnumName, Members), WriteError))
		{
			Result.Warnings.Add(WriteError);
			return;
		}
		Result.Headers.Add(HeaderName + TEXT(".h"));
		++Result.EnumCount;
	};

	EmitEnum(TEXT("FlockShopItemId"), FFlockEnumEmitter::CollectShopItems(Snapshot));
	EmitEnum(TEXT("FlockCurrencyId"), FFlockEnumEmitter::CollectCurrencies(Snapshot));
	EmitEnum(TEXT("FlockAchievementId"), FFlockEnumEmitter::CollectAchievements(Snapshot));

	// The member → declared-name table, and the calls that install it.
	//
	// Emitted as **data the module registers**, not as UPROPERTY metadata: `FField`'s metadata map lives
	// behind `WITH_METADATA` and is stripped from a packaged build, so a meta-driven mapping would resolve
	// in the editor and silently write C++ spellings in a shipping build. Always written, even when the
	// table is empty, because the module implementation includes it unconditionally.
	FString Table = Banner;
	Table += TEXT("\n#pragma once\n\n#include \"CoreMinimal.h\"\n\n");
	Table += FString::Printf(
		TEXT("/** Installs this module's member -> declared-name mappings into the SDK's struct binder. */\n")
		TEXT("namespace %sWireNames\n{\n")
		TEXT("\tvoid Register();\n")
		TEXT("\tvoid Unregister();\n")
		TEXT("}\n"), *ModuleName);

	FString TableSource = Banner;
	TableSource += FString::Printf(TEXT("\n#include \"%sWireNames.h\"\n\n"), *ModuleName);
	TableSource += TEXT("#include \"Codegen/FlockStructBinder.h\"\n");
	// The headers actually written, not one per struct: a nested struct is hoisted to the top level of
	// its *parent's* header and has no file of its own, so naming a header after it would not resolve.
	for (const FString& Header : Result.Headers)
	{
		TableSource += FString::Printf(TEXT("#include \"%s\"\n"), *Header);
	}
	TableSource += FString::Printf(TEXT("\nvoid %sWireNames::Register()\n{\n"), *ModuleName);
	for (const TPair<FString, TMap<FString, FString>>& Entry : WireNames)
	{
		TableSource += FString::Printf(
			TEXT("\tFFlockStructBinder::RegisterWireNames(%s::StaticStruct(), {\n"), *Entry.Key);
		for (const TPair<FString, FString>& Pair : Entry.Value)
		{
			TableSource += FString::Printf(TEXT("\t\t{ TEXT(\"%s\"), TEXT(\"%s\") },\n"),
				*Pair.Key, *Pair.Value);
		}
		TableSource += TEXT("\t});\n");
	}
	TableSource += TEXT("}\n\n");
	TableSource += FString::Printf(TEXT("void %sWireNames::Unregister()\n{\n"), *ModuleName);
	for (const TPair<FString, TMap<FString, FString>>& Entry : WireNames)
	{
		TableSource += FString::Printf(
			TEXT("\tFFlockStructBinder::UnregisterWireNames(%s::StaticStruct());\n"), *Entry.Key);
	}
	TableSource += TEXT("}\n");

	const FString PrivateDir = FPaths::Combine(GeneratedRoot, TEXT("Private"));
	IFileManager::Get().MakeDirectory(*PrivateDir, /*Tree*/ true);

	FString TableError;
	if (!WriteIfChanged(FPaths::Combine(PublicDir, ModuleName + TEXT("WireNames.h")), Table, TableError)
		|| !WriteIfChanged(FPaths::Combine(PrivateDir, ModuleName + TEXT("WireNames.cpp")), TableSource, TableError))
	{
		Result.Error = TableError;
		return Result;
	}
	Result.Headers.Add(ModuleName + TEXT("WireNames.h"));

	Result.bSucceeded = true;
	return Result;
}
