// Copyright 2022, Qwacks. Licensed under the MIT License - see LICENSE.md.

#include "Codegen/FlockCppModuleEmitter.h"

#include "HAL/FileManager.h"
#include "HAL/PlatformFileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "ProjectDescriptor.h"

namespace
{
	// No copyright line — see the note in FlockCppTypeEmitter.cpp: these files are generated into the
	// user's project from their own schema.
	const TCHAR* const GeneratedBanner =
		TEXT("// <auto-generated>\n")
		TEXT("//   Generated by Flock. Do not edit by hand — a schema sync replaces this file.\n")
		TEXT("// </auto-generated>\n");

	/** Writes only when the content differs, so a re-sync doesn't churn timestamps and force a rebuild. */
	bool WriteIfChanged(const FString& Path, const FString& Content, FString& OutError)
	{
		FString Existing;
		if (FFileHelper::LoadFileToString(Existing, *Path) && Existing.Equals(Content, ESearchCase::CaseSensitive))
		{
			return true;
		}
		if (!FFileHelper::SaveStringToFile(Content, *Path, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			OutError = FString::Printf(TEXT("Could not write '%s'. Is it read-only?"), *Path);
			return false;
		}
		return true;
	}

	FString BuildCsContents(const FString& ModuleName)
	{
		// Depends on Flock because every generated accessor calls the SDK, and on CoreUObject/Engine
		// because the emitted types are USTRUCTs. Kept minimal deliberately: a dependency added here is
		// one every consuming project inherits.
		return FString::Printf(
			TEXT("%s")
			TEXT("\n")
			TEXT("using UnrealBuildTool;\n")
			TEXT("\n")
			TEXT("public class %s : ModuleRules\n")
			TEXT("{\n")
			TEXT("\tpublic %s(ReadOnlyTargetRules Target) : base(Target)\n")
			TEXT("\t{\n")
			TEXT("\t\tPCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;\n")
			TEXT("\n")
			TEXT("\t\tPublicDependencyModuleNames.AddRange(\n")
			TEXT("\t\t\tnew string[]\n")
			TEXT("\t\t\t{\n")
			TEXT("\t\t\t\t\"Core\",\n")
			TEXT("\t\t\t\t\"CoreUObject\",\n")
			TEXT("\t\t\t\t\"Engine\",\n")
			TEXT("\t\t\t\t\"Flock\",\n")
			TEXT("\t\t\t}\n")
			TEXT("\t\t\t);\n")
			TEXT("\t}\n")
			TEXT("}\n"),
			GeneratedBanner, *ModuleName, *ModuleName);
	}

	FString ModuleCppContents(const FString& ModuleName)
	{
		// A real module implementation rather than FDefaultModuleImpl, because the generated structs'
		// declared wire names have to be installed into the SDK's binder before anything reads or writes
		// one — and removed on unload, so a hot-reloaded module leaves no stale struct pointers behind.
		return FString::Printf(
			TEXT("%s")
			TEXT("\n")
			TEXT("#include \"Modules/ModuleManager.h\"\n")
			TEXT("#include \"%sWireNames.h\"\n")
			TEXT("\n")
			TEXT("class F%sModule : public IModuleInterface\n")
			TEXT("{\n")
			TEXT("public:\n")
			TEXT("\tvirtual void StartupModule() override { %sWireNames::Register(); }\n")
			TEXT("\tvirtual void ShutdownModule() override { %sWireNames::Unregister(); }\n")
			TEXT("};\n")
			TEXT("\n")
			TEXT("IMPLEMENT_MODULE(F%sModule, %s);\n"),
			GeneratedBanner, *ModuleName, *ModuleName, *ModuleName, *ModuleName, *ModuleName, *ModuleName);
	}

	/**
	 * The wire-name table's declaration, and an **empty** implementation of it.
	 *
	 * Part of the skeleton, not of the type emitter's output, even though the type emitter overwrites the
	 * implementation with the real table. The module implementation includes this header unconditionally,
	 * so if it only appeared alongside generated types then a sync that failed after the skeleton — or a
	 * clean — would leave a module that cannot compile. The skeleton has to stand on its own.
	 */
	FString WireNamesHeaderContents(const FString& ModuleName)
	{
		return FString::Printf(
			TEXT("%s")
			TEXT("\n")
			TEXT("#pragma once\n")
			TEXT("\n")
			TEXT("#include \"CoreMinimal.h\"\n")
			TEXT("\n")
			TEXT("/** Installs this module's member -> declared-name mappings into the SDK's struct binder. */\n")
			TEXT("namespace %sWireNames\n")
			TEXT("{\n")
			TEXT("\tvoid Register();\n")
			TEXT("\tvoid Unregister();\n")
			TEXT("}\n"),
			GeneratedBanner, *ModuleName);
	}

	FString WireNamesStubContents(const FString& ModuleName)
	{
		return FString::Printf(
			TEXT("%s")
			TEXT("\n")
			TEXT("#include \"%sWireNames.h\"\n")
			TEXT("\n")
			TEXT("// No generated types yet, so there is nothing to register. A schema sync replaces this.\n")
			TEXT("void %sWireNames::Register()\n{\n}\n")
			TEXT("\n")
			TEXT("void %sWireNames::Unregister()\n{\n}\n"),
			GeneratedBanner, *ModuleName, *ModuleName, *ModuleName);
	}

	/**
	 * The manifest as compiled constants.
	 *
	 * The JSON sidecar stays the source of truth for tooling — the editor has to answer "is this stale?"
	 * before this header has ever compiled — so this is the runtime-readable copy, not a replacement.
	 */
	FString ManifestHeaderContents(const FString& ModuleName, const FFlockCodegenManifest& Manifest)
	{
		return FString::Printf(
			TEXT("%s")
			TEXT("\n")
			TEXT("#pragma once\n")
			TEXT("\n")
			TEXT("#include \"CoreMinimal.h\"\n")
			TEXT("\n")
			TEXT("/** What the sync that produced this module generated from. */\n")
			TEXT("namespace %sManifest\n")
			TEXT("{\n")
			TEXT("\tinline const TCHAR* const GameVersionId = TEXT(\"%s\");\n")
			TEXT("\tinline const TCHAR* const ContentHash = TEXT(\"%s\");\n")
			TEXT("\tinline const TCHAR* const GeneratedAtUtc = TEXT(\"%s\");\n")
			TEXT("\tinline const TCHAR* const SdkVersion = TEXT(\"%s\");\n")
			TEXT("\n")
			TEXT("\tinline constexpr int32 PlayerTemplateCount = %d;\n")
			TEXT("\tinline constexpr int32 GameConfigCount = %d;\n")
			TEXT("\tinline constexpr int32 ShopCount = %d;\n")
			TEXT("}\n"),
			GeneratedBanner, *ModuleName,
			*Manifest.GameVersionId, *Manifest.ContentHash, *Manifest.GeneratedAtUtc, *Manifest.SdkVersion,
			Manifest.PlayerTemplateCount, Manifest.GameConfigCount, Manifest.ShopCount);
	}
}

FString FFlockCppModuleEmitter::ModuleNameFromRoot(const FString& GeneratedRoot)
{
	FString Normalized = GeneratedRoot;
	FPaths::NormalizeDirectoryName(Normalized);
	return FPaths::GetCleanFilename(Normalized);
}

bool FFlockCppModuleEmitter::ProjectHasCppTargets(const FString& ProjectDir)
{
	const FString SourceDir = FPaths::Combine(ProjectDir, TEXT("Source"));
	if (!IFileManager::Get().DirectoryExists(*SourceDir))
	{
		return false;
	}
	// A *.Target.cs is what makes a project buildable. A Source/ folder can exist without one — the
	// generated module's own folder would create it — so the folder alone proves nothing.
	TArray<FString> Targets;
	IFileManager::Get().FindFiles(Targets, *FPaths::Combine(SourceDir, TEXT("*.Target.cs")), true, false);
	return Targets.Num() > 0;
}

bool FFlockCppModuleEmitter::IsUnderSourceDir(const FString& GeneratedRoot, const FString& ProjectDir)
{
	FString Root = FPaths::ConvertRelativePathToFull(GeneratedRoot);
	FString SourceDir = FPaths::ConvertRelativePathToFull(FPaths::Combine(ProjectDir, TEXT("Source")));
	FPaths::NormalizeDirectoryName(Root);
	FPaths::NormalizeDirectoryName(SourceDir);
	return Root.StartsWith(SourceDir + TEXT("/"), ESearchCase::IgnoreCase);
}

bool FFlockCppModuleEmitter::RegisterModule(const FString& ProjectFilePath, const FString& ModuleName,
	bool& bOutPatched, FString& OutError)
{
	bOutPatched = false;

	FProjectDescriptor Descriptor;
	FText Failure;
	if (!Descriptor.Load(ProjectFilePath, Failure))
	{
		OutError = FString::Printf(TEXT("Could not read '%s': %s"), *ProjectFilePath, *Failure.ToString());
		return false;
	}

	// Additive and idempotent: an already-registered module leaves the file untouched, so a re-sync never
	// rewrites the project file and never reorders what is already in it.
	const FName ModuleFName(*ModuleName);
	for (const FModuleDescriptor& Module : Descriptor.Modules)
	{
		if (Module.Name == ModuleFName)
		{
			return true;
		}
	}

	if (FPlatformFileManager::Get().GetPlatformFile().IsReadOnly(*ProjectFilePath))
	{
		OutError = FString::Printf(
			TEXT("'%s' is read-only, so the generated module could not be registered. Check it out and sync again."),
			*ProjectFilePath);
		return false;
	}

	Descriptor.Modules.Add(FModuleDescriptor(ModuleFName, EHostType::Runtime, ELoadingPhase::Default));
	if (!Descriptor.Save(ProjectFilePath, Failure))
	{
		OutError = FString::Printf(TEXT("Could not write '%s': %s"), *ProjectFilePath, *Failure.ToString());
		return false;
	}

	bOutPatched = true;
	return true;
}

bool FFlockCppModuleEmitter::UnregisterModule(const FString& ProjectFilePath, const FString& ModuleName,
	bool& bOutPatched, FString& OutError)
{
	bOutPatched = false;

	FProjectDescriptor Descriptor;
	FText Failure;
	if (!Descriptor.Load(ProjectFilePath, Failure))
	{
		OutError = FString::Printf(TEXT("Could not read '%s': %s"), *ProjectFilePath, *Failure.ToString());
		return false;
	}

	const FName ModuleFName(*ModuleName);
	const int32 Removed = Descriptor.Modules.RemoveAll(
		[&ModuleFName](const FModuleDescriptor& Module) { return Module.Name == ModuleFName; });
	if (Removed == 0)
	{
		return true;
	}

	if (FPlatformFileManager::Get().GetPlatformFile().IsReadOnly(*ProjectFilePath))
	{
		OutError = FString::Printf(TEXT("'%s' is read-only, so the module entry could not be removed."),
			*ProjectFilePath);
		return false;
	}
	if (!Descriptor.Save(ProjectFilePath, Failure))
	{
		OutError = FString::Printf(TEXT("Could not write '%s': %s"), *ProjectFilePath, *Failure.ToString());
		return false;
	}

	bOutPatched = true;
	return true;
}

FFlockCppModuleEmitter::FEmitResult FFlockCppModuleEmitter::Emit(const FString& GeneratedRoot,
	const FFlockCodegenManifest& Manifest, const FString& ProjectFilePath)
{
	FEmitResult Result;
	Result.ModuleName = ModuleNameFromRoot(GeneratedRoot);
	if (Result.ModuleName.IsEmpty())
	{
		Result.Error = TEXT("Could not derive a module name from the Generated Code Path.");
		return Result;
	}

	const FString ProjectDir = FPaths::GetPath(ProjectFilePath);

	// Refused rather than converted — see the header. The message names the way out, because "this
	// project has no C++" is not something a designer can be expected to act on unaided.
	if (!ProjectHasCppTargets(ProjectDir))
	{
		Result.Error = TEXT("This is a Blueprint-only project, so a C++ module cannot be added to it. "
			"Set Codegen Target back to Blueprint, or add a C++ class to the project first "
			"(Tools > New C++ Class) and sync again.");
		return Result;
	}
	if (!IsUnderSourceDir(GeneratedRoot, ProjectDir))
	{
		Result.Error = FString::Printf(
			TEXT("The C++ target needs Generated Code Path under the project's Source folder, or the module "
				"will never be compiled. '%s' is outside it."), *GeneratedRoot);
		return Result;
	}

	const FString PrivateDir = FPaths::Combine(GeneratedRoot, TEXT("Private"));
	const FString PublicDir = FPaths::Combine(GeneratedRoot, TEXT("Public"));
	IFileManager::Get().MakeDirectory(*PrivateDir, /*Tree*/ true);
	IFileManager::Get().MakeDirectory(*PublicDir, /*Tree*/ true);

	FString WriteError;
	const FString BuildCsPath = FPaths::Combine(GeneratedRoot, Result.ModuleName + TEXT(".Build.cs"));
	if (!WriteIfChanged(BuildCsPath, BuildCsContents(Result.ModuleName), WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}
	if (!WriteIfChanged(FPaths::Combine(PrivateDir, Result.ModuleName + TEXT("Module.cpp")),
		ModuleCppContents(Result.ModuleName), WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}
	if (!WriteIfChanged(FPaths::Combine(PublicDir, Result.ModuleName + TEXT("Manifest.h")),
		ManifestHeaderContents(Result.ModuleName, Manifest), WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}
	// The wire-name header always; its implementation only when absent, so a re-sync does not clobber the
	// real table the type emitter writes moments later.
	if (!WriteIfChanged(FPaths::Combine(PublicDir, Result.ModuleName + TEXT("WireNames.h")),
		WireNamesHeaderContents(Result.ModuleName), WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}
	const FString WireNamesSource = FPaths::Combine(PrivateDir, Result.ModuleName + TEXT("WireNames.cpp"));
	if (!IFileManager::Get().FileExists(*WireNamesSource)
		&& !WriteIfChanged(WireNamesSource, WireNamesStubContents(Result.ModuleName), WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}

	FString RegisterError;
	if (!RegisterModule(ProjectFilePath, Result.ModuleName, Result.bProjectFilePatched, RegisterError))
	{
		Result.Error = RegisterError;
		return Result;
	}

	Result.bSucceeded = true;
	return Result;
}

FFlockCppModuleEmitter::FEmitResult FFlockCppModuleEmitter::EmitForProject(const FString& GeneratedRoot,
	const FFlockCodegenManifest& Manifest)
{
	return Emit(GeneratedRoot, Manifest, FPaths::ConvertRelativePathToFull(FPaths::GetProjectFilePath()));
}

bool FFlockCppModuleEmitter::RemoveGeneratedTypes(const FString& GeneratedRoot, const FString& ModuleName,
	bool bResetManifest, FString& OutError)
{
	const FString PublicDir = FPaths::Combine(GeneratedRoot, TEXT("Public"));
	const FString PrivateDir = FPaths::Combine(GeneratedRoot, TEXT("Private"));
	const FString ManifestHeader = ModuleName + TEXT("Manifest.h");
	const FString WireNamesHeader = ModuleName + TEXT("WireNames.h");
	const FString WireNamesSource = ModuleName + TEXT("WireNames.cpp");
	const FString ModuleSource = ModuleName + TEXT("Module.cpp");

	// Public: every generated header goes except the two the skeleton owns. The module implementation
	// includes both unconditionally, so removing either leaves a project that will not compile.
	TArray<FString> Headers;
	IFileManager::Get().FindFiles(Headers, *FPaths::Combine(PublicDir, TEXT("*.h")), /*Files*/ true, /*Dirs*/ false);
	for (const FString& File : Headers)
	{
		if (!File.Equals(ManifestHeader, ESearchCase::IgnoreCase)
			&& !File.Equals(WireNamesHeader, ESearchCase::IgnoreCase))
		{
			IFileManager::Get().Delete(*FPaths::Combine(PublicDir, File));
		}
	}

	// Private: the accessors go, the module implementation stays — without it the module links but never
	// loads, which presents as its types not existing.
	TArray<FString> Sources;
	IFileManager::Get().FindFiles(Sources, *FPaths::Combine(PrivateDir, TEXT("*.cpp")), /*Files*/ true, /*Dirs*/ false);
	for (const FString& File : Sources)
	{
		if (!File.Equals(ModuleSource, ESearchCase::IgnoreCase)
			&& !File.Equals(WireNamesSource, ESearchCase::IgnoreCase))
		{
			IFileManager::Get().Delete(*FPaths::Combine(PrivateDir, File));
		}
	}

	// Emptied rather than deleted, for the same reason as the manifest: the table names structs that no
	// longer exist, so it must stop registering them — but the symbols it defines must still be there.
	FString StubError;
	if (!WriteIfChanged(FPaths::Combine(PrivateDir, WireNamesSource), WireNamesStubContents(ModuleName), StubError))
	{
		OutError = StubError;
		return false;
	}

	if (bResetManifest)
	{
		// Emptied rather than deleted: anything including it has to keep compiling, and it must stop
		// claiming a version that nothing was generated for.
		FFlockCodegenManifest Empty;
		return WriteIfChanged(FPaths::Combine(PublicDir, ManifestHeader),
			ManifestHeaderContents(ModuleName, Empty), OutError);
	}
	return true;
}
