// Copyright 2022, Qwacks. Licensed under the MIT License - see LICENSE.md.

#include "Codegen/FlockCppAccessorEmitter.h"

#include "Codegen/FlockCppTypeEmitter.h"
#include "Codegen/FlockEnumEmitter.h"
#include "Codegen/FlockStructEmitter.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace
{
	// No copyright line — see the note in FlockCppTypeEmitter.cpp: these files are generated into the
	// user's project from their own schema.
	const TCHAR* const Banner =
		TEXT("// <auto-generated>\n")
		TEXT("//   Generated by Flock. Do not edit by hand — a schema sync replaces this file.\n")
		TEXT("// </auto-generated>\n");

	const TCHAR* const CurrencyTag = TEXT("currency");

	FString PascalCase(const FString& Source)
	{
		FString Pascal;
		bool bUpperNext = true;
		for (const TCHAR Character : Source)
		{
			if (FChar::IsAlnum(Character))
			{
				Pascal.AppendChar(bUpperNext ? FChar::ToUpper(Character) : Character);
				bUpperNext = false;
			}
			else
			{
				bUpperNext = true;
			}
		}
		if (Pascal.IsEmpty())
		{
			return TEXT("Unnamed");
		}
		return FChar::IsDigit(Pascal[0]) ? TEXT("_") + Pascal : Pascal;
	}

	/** Reserves a name, disambiguating by kind before a number — same rule as the macro library. */
	FString Reserve(const FString& Base, const TCHAR* KindSuffix, TSet<FString>& Used)
	{
		FString Candidate = Base;
		if (Used.Contains(Candidate))
		{
			Candidate = Base + KindSuffix;
		}
		int32 Suffix = 2;
		while (Used.Contains(Candidate))
		{
			Candidate = FString::Printf(TEXT("%s%s_%d"), *Base, KindSuffix, Suffix++);
		}
		Used.Add(Candidate);
		return Candidate;
	}

	/** The template whose row holds the wallet; baking its id skips the SDK's runtime tag scan. */
	FString FindCurrencyTemplateId(const FFlockSchemaSnapshot& Snapshot)
	{
		for (const FFlockPlayerTemplateSchema& Template : Snapshot.PlayerTemplates)
		{
			if (Template.Tag.Equals(CurrencyTag, ESearchCase::IgnoreCase))
			{
				return Template.Id;
			}
		}
		return FString();
	}

	bool WriteIfChanged(const FString& Path, const FString& Content, FString& OutError)
	{
		FString Existing;
		if (FFileHelper::LoadFileToString(Existing, *Path) && Existing.Equals(Content, ESearchCase::CaseSensitive))
		{
			return true;
		}
		if (!FFileHelper::SaveStringToFile(Content, *Path, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			OutError = FString::Printf(TEXT("Could not write '%s'. Is it read-only?"), *Path);
			return false;
		}
		return true;
	}
}

FFlockCppAccessorEmitter::FEmitResult FFlockCppAccessorEmitter::Emit(const FFlockSchemaSnapshot& Snapshot,
	const FString& GeneratedRoot, const FString& ModuleName)
{
	FEmitResult Result;

	const FString ModuleApi = ModuleName.ToUpper() + TEXT("_API");
	const FString HeaderName = ModuleName + TEXT("Accessors");

	FString Declarations;
	FString Definitions;
	FString Includes;
	TSet<FString> UsedNames;

	auto AddInclude = [&Includes](const FString& Header)
	{
		Includes += FString::Printf(TEXT("#include \"%s.h\"\n"), *Header);
	};

	// ── Player templates: fetch into the typed struct, write it back ──
	for (const FFlockPlayerTemplateSchema& Template : Snapshot.PlayerTemplates)
	{
		if (Template.Id.IsEmpty())
		{
			continue;
		}
		const FString StructName = FFlockCppTypeEmitter::MakeStructName(
			Template.Name, FFlockStructEmitter::TemplateSuffix);
		AddInclude(StructName);

		const FString Entity = PascalCase(Template.Name);
		const FString GetName = Reserve(TEXT("Get") + Entity, TEXT("Template"), UsedNames);
		const FString SaveName = Reserve(TEXT("Save") + Entity, TEXT("Template"), UsedNames);

		Declarations += FString::Printf(
			TEXT("\t/**\n")
			TEXT("\t * Resolves the signed-in player's \"%s\" row into a typed struct.\n")
			TEXT("\t *\n")
			TEXT("\t * The row id comes back alongside it because Save needs it and nothing else can supply it —\n")
			TEXT("\t * it identifies this player's row. It is deliberately not a member of the struct.\n")
			TEXT("\t */\n")
			TEXT("\tstatic void %s(const UObject* WorldContextObject,\n")
			TEXT("\t\tTFunction<void(TFlockResult<%s>, const FString& RowId)> OnDone);\n\n"),
			*Template.Name, *GetName, *StructName);

		Declarations += FString::Printf(
			TEXT("\t/** Writes a \"%s\" struct back to the row it came from. */\n")
			TEXT("\tstatic void %s(const UObject* WorldContextObject, const FString& RowId,\n")
			TEXT("\t\tconst %s& Value, TFunction<void(TFlockResult<FFlockPlayerData>)> OnDone);\n\n"),
			*Template.Name, *SaveName, *StructName);

		Definitions += FString::Printf(
			TEXT("void FFlockGenerated::%s(const UObject* WorldContextObject,\n")
			TEXT("\tTFunction<void(TFlockResult<%s>, const FString& RowId)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockPlayerProvider* Provider = ResolvePlayer(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<%s>::Fail(NotReady()), FString()); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\tProvider->GetMyDataByTemplate(TEXT(\"%s\"), [OnDone](TFlockResult<FFlockPlayerData> Row)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (!OnDone)\n")
			TEXT("\t\t{\n")
			TEXT("\t\t\treturn;\n")
			TEXT("\t\t}\n")
			TEXT("\t\tif (!Row.bSuccess)\n")
			TEXT("\t\t{\n")
			TEXT("\t\t\tOnDone(TFlockResult<%s>::Fail(Row.Error), FString());\n")
			TEXT("\t\t\treturn;\n")
			TEXT("\t\t}\n")
			TEXT("\t\t%s Value;\n")
			TEXT("\t\tFFlockStructBinder::FillStruct(%s::StaticStruct(), &Value, Row.Value.Data);\n")
			TEXT("\t\tOnDone(TFlockResult<%s>::Ok(Value), Row.Value.Id);\n")
			TEXT("\t});\n")
			TEXT("}\n\n"),
			*GetName, *StructName, *StructName, *Template.Id, *StructName, *StructName, *StructName, *StructName);

		Definitions += FString::Printf(
			TEXT("void FFlockGenerated::%s(const UObject* WorldContextObject, const FString& RowId,\n")
			TEXT("\tconst %s& Value, TFunction<void(TFlockResult<FFlockPlayerData>)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockCommandProvider* Provider = ResolveCommands(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<FFlockPlayerData>::Fail(NotReady())); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\t// Members are named exactly as the template declares them, so the body needs no name map.\n")
			TEXT("\tconst FFlockCommandData Data = FFlockStructBinder::ToCommandData(%s::StaticStruct(), &Value);\n")
			TEXT("\tProvider->UpdatePlayerData(RowId, Data, [OnDone](TFlockResult<FFlockPlayerData> R) { if (OnDone) { OnDone(R); } });\n")
			TEXT("}\n\n"),
			*SaveName, *StructName, *StructName);

		Result.FunctionCount += 2;
	}

	// ── Game configs: read-only, so a Get and no Save ──
	for (const FFlockGameConfigSchema& Config : Snapshot.GameConfigs)
	{
		if (Config.Id.IsEmpty())
		{
			continue;
		}
		const FString StructName = FFlockCppTypeEmitter::MakeStructName(
			Config.Name, FFlockStructEmitter::ConfigSuffix);
		AddInclude(StructName);

		const FString GetName = Reserve(TEXT("Get") + PascalCase(Config.Name), TEXT("Config"), UsedNames);

		Declarations += FString::Printf(
			TEXT("\t/** Reads the \"%s\" game config, patched value where one applies. */\n")
			TEXT("\tstatic void %s(const UObject* WorldContextObject,\n")
			TEXT("\t\tTFunction<void(TFlockResult<%s>)> OnDone);\n\n"),
			*Config.Name, *GetName, *StructName);

		Definitions += FString::Printf(
			TEXT("void FFlockGenerated::%s(const UObject* WorldContextObject,\n")
			TEXT("\tTFunction<void(TFlockResult<%s>)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockConfigProvider* Provider = ResolveConfig(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<%s>::Fail(NotReady())); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\tProvider->ResolveConfigData(TEXT(\"%s\"), [OnDone](TFlockResult<FFlockStructuredData> Data)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (!OnDone)\n")
			TEXT("\t\t{\n")
			TEXT("\t\t\treturn;\n")
			TEXT("\t\t}\n")
			TEXT("\t\tif (!Data.bSuccess)\n")
			TEXT("\t\t{\n")
			TEXT("\t\t\tOnDone(TFlockResult<%s>::Fail(Data.Error));\n")
			TEXT("\t\t\treturn;\n")
			TEXT("\t\t}\n")
			TEXT("\t\t%s Value;\n")
			TEXT("\t\tFFlockStructBinder::FillStruct(%s::StaticStruct(), &Value, Data.Value);\n")
			TEXT("\t\tOnDone(TFlockResult<%s>::Ok(Value));\n")
			TEXT("\t});\n")
			TEXT("}\n\n"),
			*GetName, *StructName, *StructName, *Config.Id, *StructName, *StructName, *StructName, *StructName);

		++Result.FunctionCount;
	}

	// ── Commands, keyed by the generated enums ──
	const bool bHasShopItems = FFlockEnumEmitter::CollectShopItems(Snapshot).Num() > 0;
	const bool bHasAchievements = FFlockEnumEmitter::CollectAchievements(Snapshot).Num() > 0;
	const bool bHasCurrencies = FFlockEnumEmitter::CollectCurrencies(Snapshot).Num() > 0;

	if (bHasShopItems)
	{
		AddInclude(TEXT("FlockShopItemId"));
		Declarations +=
			TEXT("\t/** Buys a shop item for the signed-in player. Never retried on an ambiguous failure. */\n")
			TEXT("\tstatic void Purchase(const UObject* WorldContextObject, EFlockShopItemId Item,\n")
			TEXT("\t\tTFunction<void(TFlockResult<FFlockPlayerInventory>)> OnDone);\n\n");

		Definitions +=
			TEXT("void FFlockGenerated::Purchase(const UObject* WorldContextObject, EFlockShopItemId Item,\n")
			TEXT("\tTFunction<void(TFlockResult<FFlockPlayerInventory>)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockShopProvider* Provider = ResolveShop(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<FFlockPlayerInventory>::Fail(NotReady())); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\t// The signed-in-player overload - no id to resolve or pass.\n")
			TEXT("\tProvider->Purchase(FlockShopItemIdToWire(Item),\n")
			TEXT("\t\t[OnDone](TFlockResult<FFlockPlayerInventory> R) { if (OnDone) { OnDone(R); } });\n")
			TEXT("}\n\n");
		++Result.FunctionCount;
	}

	if (bHasAchievements)
	{
		AddInclude(TEXT("FlockAchievementId"));
		Declarations +=
			TEXT("\t/** Unlocks an achievement on the signed-in player's achievement row. */\n")
			TEXT("\tstatic void UnlockAchievement(const UObject* WorldContextObject, EFlockAchievementId Achievement,\n")
			TEXT("\t\tTFunction<void(TFlockResult<FFlockPlayerData>)> OnDone);\n\n");

		Definitions +=
			TEXT("void FFlockGenerated::UnlockAchievement(const UObject* WorldContextObject,\n")
			TEXT("\tEFlockAchievementId Achievement, TFunction<void(TFlockResult<FFlockPlayerData>)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockCommandProvider* Provider = ResolveCommands(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<FFlockPlayerData>::Fail(NotReady())); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\tProvider->UnlockAchievement(FlockAchievementIdToWire(Achievement),\n")
			TEXT("\t\t[OnDone](TFlockResult<FFlockPlayerData> R) { if (OnDone) { OnDone(R); } });\n")
			TEXT("}\n\n");
		++Result.FunctionCount;
	}

	if (bHasCurrencies)
	{
		AddInclude(TEXT("FlockCurrencyId"));
		Declarations +=
			TEXT("\t/**\n")
			TEXT("\t * Credits the signed-in player's wallet.\n")
			TEXT("\t *\n")
			TEXT("\t * Money-safe: never queued when offline, and never re-sent after an ambiguous failure.\n")
			TEXT("\t */\n")
			TEXT("\tstatic void AddFunds(const UObject* WorldContextObject, EFlockCurrencyId Currency, int32 Amount,\n")
			TEXT("\t\tTFunction<void(TFlockResult<FFlockPlayerData>)> OnDone);\n\n");

		const FString CurrencyTemplateId = FindCurrencyTemplateId(Snapshot);
		if (CurrencyTemplateId.IsEmpty())
		{
			// Not fatal: the SDK resolves the wallet by tag when no id is supplied. A slower call, not a
			// broken one — but worth saying, because the tag is probably missing by accident.
			Result.Warnings.Add(TEXT("No template is tagged 'currency', so Add Funds will resolve the wallet "
				"at runtime instead of using a baked id."));
		}

		Definitions += FString::Printf(
			TEXT("void FFlockGenerated::AddFunds(const UObject* WorldContextObject, EFlockCurrencyId Currency,\n")
			TEXT("\tint32 Amount, TFunction<void(TFlockResult<FFlockPlayerData>)> OnDone)\n")
			TEXT("{\n")
			TEXT("\tFFlockCommandProvider* Provider = ResolveCommands(WorldContextObject);\n")
			TEXT("\tif (!Provider)\n")
			TEXT("\t{\n")
			TEXT("\t\tif (OnDone) { OnDone(TFlockResult<FFlockPlayerData>::Fail(NotReady())); }\n")
			TEXT("\t\treturn;\n")
			TEXT("\t}\n")
			TEXT("\t// The currency-tagged template's id is baked, so the call skips the runtime tag scan.\n")
			TEXT("\tProvider->AddGameFunds(FlockCurrencyIdToWire(Currency), Amount, TEXT(\"%s\"),\n")
			TEXT("\t\t[OnDone](TFlockResult<FFlockPlayerData> R) { if (OnDone) { OnDone(R); } });\n")
			TEXT("}\n\n"),
			*CurrencyTemplateId);
		++Result.FunctionCount;
	}

	// ── Assemble ──
	FString Header = Banner;
	Header += TEXT("\n#pragma once\n\n");
	Header += TEXT("#include \"CoreMinimal.h\"\n");
	Header += TEXT("#include \"Http/FlockResult.h\"\n");
	Header += TEXT("#include \"Models/FlockPlayerModels.h\"\n");
	Header += TEXT("#include \"Models/FlockShopModels.h\"\n");
	Header += Includes;
	Header += TEXT("\n");
	Header += FString::Printf(
		TEXT("/**\n")
		TEXT(" * Typed access to this game version's content.\n")
		TEXT(" *\n")
		TEXT(" * Every function resolves the SDK from the world context, so no call site holds a subsystem or a\n")
		TEXT(" * provider. A call made before the SDK has initialized fails through its callback rather than\n")
		TEXT(" * crashing.\n")
		TEXT(" */\n")
		TEXT("struct %s FFlockGenerated\n")
		TEXT("{\n%s};\n"),
		*ModuleApi, *Declarations);

	FString Source = Banner;
	Source += FString::Printf(TEXT("\n#include \"%s.h\"\n\n"), *HeaderName);
	Source += TEXT("#include \"Codegen/FlockStructBinder.h\"\n");
	Source += TEXT("#include \"FlockSubsystem.h\"\n");
	Source += TEXT("#include \"Providers/FlockCommandProvider.h\"\n");
	Source += TEXT("#include \"Providers/FlockConfigProvider.h\"\n");
	Source += TEXT("#include \"Providers/FlockPlayerProvider.h\"\n");
	Source += TEXT("#include \"Providers/FlockShopProvider.h\"\n\n");
	Source +=
		TEXT("namespace\n")
		TEXT("{\n")
		TEXT("\t/** The failure every accessor reports when the SDK is not up yet. */\n")
		TEXT("\tFFlockError NotReady()\n")
		TEXT("\t{\n")
		TEXT("\t\treturn FFlockError::Make(EFlockErrorType::Validation,\n")
		TEXT("\t\t\tTEXT(\"The Flock SDK is not initialized, or the world context could not resolve it.\"));\n")
		TEXT("\t}\n")
		TEXT("\n")
		TEXT("\tFFlockPlayerProvider* ResolvePlayer(const UObject* WorldContextObject)\n")
		TEXT("\t{\n")
		TEXT("\t\tUFlockSubsystem* Flock = UFlockSubsystem::Get(WorldContextObject);\n")
		TEXT("\t\treturn Flock ? Flock->GetPlayerProvider() : nullptr;\n")
		TEXT("\t}\n")
		TEXT("\n")
		TEXT("\tFFlockConfigProvider* ResolveConfig(const UObject* WorldContextObject)\n")
		TEXT("\t{\n")
		TEXT("\t\tUFlockSubsystem* Flock = UFlockSubsystem::Get(WorldContextObject);\n")
		TEXT("\t\treturn Flock ? Flock->GetConfigProvider() : nullptr;\n")
		TEXT("\t}\n")
		TEXT("\n")
		TEXT("\tFFlockCommandProvider* ResolveCommands(const UObject* WorldContextObject)\n")
		TEXT("\t{\n")
		TEXT("\t\tUFlockSubsystem* Flock = UFlockSubsystem::Get(WorldContextObject);\n")
		TEXT("\t\treturn Flock ? Flock->GetCommandProvider() : nullptr;\n")
		TEXT("\t}\n")
		TEXT("\n")
		TEXT("\tFFlockShopProvider* ResolveShop(const UObject* WorldContextObject)\n")
		TEXT("\t{\n")
		TEXT("\t\tUFlockSubsystem* Flock = UFlockSubsystem::Get(WorldContextObject);\n")
		TEXT("\t\treturn Flock ? Flock->GetShopProvider() : nullptr;\n")
		TEXT("\t}\n")
		TEXT("}\n\n");
	Source += Definitions;

	const FString PublicDir = FPaths::Combine(GeneratedRoot, TEXT("Public"));
	const FString PrivateDir = FPaths::Combine(GeneratedRoot, TEXT("Private"));
	IFileManager::Get().MakeDirectory(*PublicDir, /*Tree*/ true);
	IFileManager::Get().MakeDirectory(*PrivateDir, /*Tree*/ true);

	FString WriteError;
	if (!WriteIfChanged(FPaths::Combine(PublicDir, HeaderName + TEXT(".h")), Header, WriteError)
		|| !WriteIfChanged(FPaths::Combine(PrivateDir, HeaderName + TEXT(".cpp")), Source, WriteError))
	{
		Result.Error = WriteError;
		return Result;
	}

	Result.bSucceeded = true;
	return Result;
}
